Query:
    type: object
    config:
        fields:
            me:
                type: "User"
                description: "Get user information by ID"
                args:
                    userId:
                        type: "Int!"
                        description: "User ID"
                resolve: "@=service('App\\\\GraphQL\\\\Resolver\\\\UserResolver').me(args['userId'])"
            tasks:
                type: "[Task!]!"
                description: "Get all tasks (admin)"
                resolve: "@=service('App\\\\GraphQL\\\\Resolver\\\\TaskResolver').tasks()"
            userTasks:
                type: "[Task!]!"
                description: "Get tasks for a specific user"
                args:
                    userId:
                        type: "Int!"
                        description: "User ID"
                resolve: "@=service('App\\\\GraphQL\\\\Resolver\\\\TaskResolver').userTasks(args['userId'])"
