Query:
    type: object
    config:
        fields:
            me:
                type: "User"
                description: "Get current user information"
                resolve: "@=service('App\\\\GraphQL\\\\Resolver\\\\UserResolver').me()"
