# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # User Domain Repository Interface binding
    App\Domain\User\Repository\UserRepositoryInterface:
        class: App\Infrastructure\Persistence\User\UserRepository

    # Task Domain Repository Interface binding
    App\Domain\Task\Repository\TaskRepositoryInterface:
        class: App\Infrastructure\Persistence\Task\TaskRepository

    # Data Source Strategy - JSONPlaceholder as default
    App\Application\User\Port\DataSourceStrategy:
        class: App\Infrastructure\ExternalApi\JSONPlaceholder\JSONPlaceholderClient

    # User Mapper
    App\Infrastructure\Persistence\User\UserMapper: ~

    # Task Factory
    App\Application\Task\Factory\TaskFactoryInterface:
        class: App\Application\Task\Factory\TaskFactory

    # Status Transition Strategy - Default as default
    App\Application\Task\StatusTransition\StatusTransitionStrategyInterface:
        class: App\Application\Task\StatusTransition\DefaultStatusTransitionStrategy

    # Task Handlers
    App\Application\Task\Handler\UpdateTaskStatusHandler: ~

    # Task Read Model Repository Interface binding
    App\Application\Task\Port\TaskReadModelRepositoryInterface:
        class: App\Infrastructure\Persistence\Task\TaskReadModelRepository

    # Task Id Generator Interface binding
    App\Application\Task\Port\TaskIdGeneratorInterface:
        class: App\Infrastructure\Persistence\Task\TaskIdGenerator

    # Event Store Interface binding
    App\Application\Task\Port\EventStoreInterface:
        class: App\Infrastructure\Persistence\EventStore\EventStoreRepository

    # Task Query Service Interface binding
    App\Application\Task\Query\TaskQueryServiceInterface:
        class: App\Application\Task\Query\TaskQueryService

    # Task Query Service
    App\Application\Task\Query\TaskQueryService: ~

    # GraphQL Resolvers
    App\GraphQL\Resolver\UserResolver:
        public: true
    App\GraphQL\Resolver\TaskResolver:
        public: true
